/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_user_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/spend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Spend */
        post: operations["spend_api_user_spend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily State */
        get: operations["daily_state_api_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Daily */
        post: operations["start_daily_api_daily_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily/task/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task */
        post: operations["complete_task_api_daily_task__index__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Daily */
        post: operations["claim_daily_api_daily_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dungeons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dungeons */
        get: operations["list_dungeons_api_dungeons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dungeons/enter/{rank}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enter Dungeon */
        post: operations["enter_dungeon_api_dungeons_enter__rank__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dungeons/task/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dungeon Task */
        post: operations["dungeon_task_api_dungeons_task__index__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dungeons/boss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enter Boss */
        post: operations["enter_boss_api_dungeons_boss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dungeons/boss/defeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Defeat Boss */
        post: operations["defeat_boss_api_dungeons_boss_defeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roll/hidden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hidden Roll */
        post: operations["hidden_roll_api_roll_hidden_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roll/hidden/claim/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Hidden */
        post: operations["claim_hidden_api_roll_hidden_claim__index__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roll/dungeon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dungeon Roll */
        post: operations["dungeon_roll_api_roll_dungeon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shop */
        get: operations["list_shop_api_shop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/buy/{item_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Buy Item */
        post: operations["buy_item_api_shop_buy__item_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inventory */
        get: operations["list_inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Equipment */
        get: operations["get_equipment_api_inventory_equipment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/equip/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Equip Item */
        post: operations["equip_item_api_inventory_equip__item_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class/awakening/{class_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose Awakening */
        post: operations["choose_awakening_api_class_awakening__class_key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class/jobchange/{class_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose Jobchange */
        post: operations["choose_jobchange_api_class_jobchange__class_key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AwakeningResult */
        AwakeningResult: {
            /** Class Stage1 */
            class_stage1: string;
            /** Class Name */
            class_name: string;
        };
        /** BossDefeat */
        BossDefeat: {
            /** Xp Reward */
            xp_reward: number;
            /** Gold Reward */
            gold_reward: number;
            /** Xp */
            xp: number;
            /** Gold */
            gold: number;
            loot?: components["schemas"]["LootItem"] | null;
        };
        /** BossRoom */
        BossRoom: {
            boss: components["schemas"]["Enemy"];
            /** Time Left */
            time_left: number;
        };
        /** BoughtItem */
        BoughtItem: {
            /** Name */
            name: string;
            /** Rarity */
            rarity: string;
            /** Slot */
            slot: string;
            /** Strength */
            strength: number;
            /** Intelligence */
            intelligence: number;
            /** Agility */
            agility: number;
            /** Vitality */
            vitality: number;
            /** Sense */
            sense: number;
        };
        /** BuyResult */
        BuyResult: {
            /** Gold */
            gold: number;
            item: components["schemas"]["BoughtItem"];
        };
        /** ClaimResult */
        ClaimResult: {
            /** Xp Gained */
            xp_gained: number;
            /** Xp */
            xp: number;
            /** Level */
            level: number;
            /** Level Ups */
            level_ups: number;
            /** Streak */
            streak: number;
            /** Stat Points */
            stat_points: number;
            /** Hidden Rolls */
            hidden_rolls: number;
        };
        /** DailyStartResult */
        DailyStartResult: {
            /** Active Quests */
            active_quests: components["schemas"]["Quest"][];
            /** Quest Progress */
            quest_progress: number;
        };
        /** DailyState */
        DailyState: {
            /** Active Quests */
            active_quests: components["schemas"]["Quest"][];
            /** Quest Progress */
            quest_progress: number;
            /** Cooldown Active */
            cooldown_active: boolean;
            /** Cooldown Remaining */
            cooldown_remaining: number;
            /** Streak */
            streak: number;
        };
        /** DungeonList */
        DungeonList: {
            /** Available Ranks */
            available_ranks: string[];
        };
        /** DungeonRollResult */
        DungeonRollResult: {
            /** Found */
            found: boolean;
            /** Dungeon Rolls */
            dungeon_rolls: number;
            /** Gate Rank */
            gate_rank?: string | null;
            /** Enemies */
            enemies?: components["schemas"]["Enemy"][] | null;
            /** Time Limit */
            time_limit?: number | null;
            /** Dungeon End */
            dungeon_end?: string | null;
        };
        /** DungeonTask */
        DungeonTask: {
            /** Dungeon Progress */
            dungeon_progress: number;
            /** Total Enemies */
            total_enemies: number;
            /** Boss Available */
            boss_available: boolean;
        };
        /** Enemy */
        Enemy: {
            /** Name */
            name: string;
            /** Task */
            task: string;
        };
        /** EnterDungeon */
        EnterDungeon: {
            /** Rank */
            rank: string;
            /** Enemies */
            enemies: components["schemas"]["Enemy"][];
            /** Time Limit */
            time_limit: number;
            /** Dungeon End */
            dungeon_end: string;
        };
        /** EquipResult */
        EquipResult: {
            equipped: components["schemas"]["InventoryItem"];
        };
        /** Equipment */
        Equipment: {
            weapon?: components["schemas"]["InventoryItem"] | null;
            armor?: components["schemas"]["InventoryItem"] | null;
            charm?: components["schemas"]["InventoryItem"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HiddenClaimResult */
        HiddenClaimResult: {
            /** Quest Name */
            quest_name: string;
            /** Xp Gained */
            xp_gained: number;
            /** Rarity */
            rarity: string;
            /** Rarity Label */
            rarity_label: string;
            /** Xp */
            xp: number;
        };
        /** HiddenQuest */
        HiddenQuest: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Xp */
            xp: number;
            /** Rarity */
            rarity: string;
            /** Rarity Label */
            rarity_label: string;
        };
        /** HiddenRollResult */
        HiddenRollResult: {
            /** Found */
            found: boolean;
            /** Hidden Rolls */
            hidden_rolls: number;
            quest?: components["schemas"]["HiddenQuest"] | null;
        };
        /** InventoryItem */
        InventoryItem: {
            /** Item Id */
            item_id: number;
            /** Item Name */
            item_name: string;
            /** Slot */
            slot: string;
            /** Rarity */
            rarity: string;
            /** Strength */
            strength: number;
            /** Intelligence */
            intelligence: number;
            /** Agility */
            agility: number;
            /** Vitality */
            vitality: number;
            /** Sense */
            sense: number;
            /** Equipped */
            equipped: number;
        };
        /** InventoryList */
        InventoryList: {
            /** Items */
            items: components["schemas"]["InventoryItem"][];
        };
        /** JobChangeResult */
        JobChangeResult: {
            /** Class Stage2 */
            class_stage2: string;
            /** Class Name */
            class_name: string;
        };
        /** LootItem */
        LootItem: {
            /** Item Name */
            item_name: string;
            /** Slot */
            slot: string;
            /** Rarity */
            rarity: string;
            /** Strength */
            strength: number;
            /** Intelligence */
            intelligence: number;
            /** Agility */
            agility: number;
            /** Vitality */
            vitality: number;
            /** Sense */
            sense: number;
        };
        /** Quest */
        Quest: {
            /** Name */
            name: string;
            /** Xp */
            xp: number;
        };
        /** ShopItem */
        ShopItem: {
            /** Name */
            name: string;
            /** Price */
            price: number;
        };
        /** ShopList */
        ShopList: {
            /** Items */
            items: components["schemas"]["ShopItem"][];
            /** Gold */
            gold: number;
        };
        /** SpendRequest */
        SpendRequest: {
            /** Stat */
            stat: string;
        };
        /** SpendResult */
        SpendResult: {
            /** Stat Points */
            stat_points: number;
            /** Str */
            str: number;
            /** Int */
            int: number;
            /** Agi */
            agi: number;
            /** Vit */
            vit: number;
            /** Sense */
            sense: number;
            equipped_bonuses: components["schemas"]["StatBlock"];
        };
        /**
         * StatBlock
         * @description The five core stats, using the short keys the UI is built around.
         *
         *     Field names intentionally mirror the UI keys (``str``/``int``/...). They
         *     shadow builtins only as attribute names, which is harmless for a schema.
         */
        StatBlock: {
            /** Str */
            str: number;
            /** Int */
            int: number;
            /** Agi */
            agi: number;
            /** Vit */
            vit: number;
            /** Sense */
            sense: number;
        };
        /** TaskProgress */
        TaskProgress: {
            /** Quest Progress */
            quest_progress: number;
            /** Total */
            total: number;
        };
        /** UserStats */
        UserStats: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Level */
            level: number;
            /** Rank */
            rank: string;
            /** Xp */
            xp: number;
            /** Xp Needed */
            xp_needed: number;
            /** Gold */
            gold: number;
            /** Streak */
            streak: number;
            /** Stat Points */
            stat_points: number;
            /** Str */
            str: number;
            /** Int */
            int: number;
            /** Agi */
            agi: number;
            /** Vit */
            vit: number;
            /** Sense */
            sense: number;
            equipped_bonuses: components["schemas"]["StatBlock"];
            /** Hidden Rolls */
            hidden_rolls: number;
            /** Dungeon Rolls */
            dungeon_rolls: number;
            /** Awakened */
            awakened: number;
            /** Job Changed */
            job_changed: number;
            /** Awakening Class */
            awakening_class?: string | null;
            /** Job Class */
            job_class?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    stats_api_user_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
        };
    };
    spend_api_user_spend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_state_api_daily_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyState"];
                };
            };
        };
    };
    start_daily_api_daily_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyStartResult"];
                };
            };
        };
    };
    complete_task_api_daily_task__index__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_daily_api_daily_claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResult"];
                };
            };
        };
    };
    list_dungeons_api_dungeons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DungeonList"];
                };
            };
        };
    };
    enter_dungeon_api_dungeons_enter__rank__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnterDungeon"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dungeon_task_api_dungeons_task__index__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DungeonTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enter_boss_api_dungeons_boss_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BossRoom"];
                };
            };
        };
    };
    defeat_boss_api_dungeons_boss_defeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BossDefeat"];
                };
            };
        };
    };
    hidden_roll_api_roll_hidden_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HiddenRollResult"];
                };
            };
        };
    };
    claim_hidden_api_roll_hidden_claim__index__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HiddenClaimResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dungeon_roll_api_roll_dungeon_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DungeonRollResult"];
                };
            };
        };
    };
    list_shop_api_shop_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopList"];
                };
            };
        };
    };
    buy_item_api_shop_buy__item_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inventory_api_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryList"];
                };
            };
        };
    };
    get_equipment_api_inventory_equipment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    equip_item_api_inventory_equip__item_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    choose_awakening_api_class_awakening__class_key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwakeningResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    choose_jobchange_api_class_jobchange__class_key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobChangeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
